
spring.application.name=poo
server.port=${PORT:8080}


# =========================
# DATABASE (ONE FILE STRATEGY)
# =========================
# If Heroku provides JDBC_DATABASE_URL, Spring will use it.
# If not, it falls back to local H2 file.
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:file:./data/testdb}
spring.datasource.username=${JDBC_DATABASE_USERNAME:sa}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${JDBC_DATABASE_DRIVER:org.h2.Driver}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Only applies when using H2; harmless elsewhere
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# =========================
# JWT
# =========================
jwt.secret=THIS_IS_A_LONG_DEV_SECRET_CHANGE_ME_123456789


# =========================
# STRIPE (PLEASE MOVE TO ENV VARS ON HEROKU)
# =========================
stripe.secret.key=sk_test_51Rfw5AQMuKMTVg9M4fZJO3PskQDd8HLe42beWTMl4LCyWMKI8KvaeWqCNLHEAO2zBkpcAkm3GGNtcDUNOGp96VKR007PB4cdDD
stripe.public.key=pk_test_51Rfw5AQMuKMTVg9MN5UEzLULEZm4Q9xHqKAkAM8fRvmwPdL95kYt3Zh9c9h9XDRy5tBxQUumukXfH0LzvZ4jc5rJ00BaN3DtTC
stripe.webhook.secret=whsec_c8024d5aeA9e788AdSe1(Peee13e3c6f0eaBa1353366916aadF019eaf69rb32


spring.main.allow-bean-definition-overriding=true
