spring.application.name=poo
server.port=${PORT:8080}


spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=never
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=your_very_long_secret_key_here
stripe.secret.key=sk_test_51Rfw5AQMuKMTVg9M4fZJO3PskQDd8HLe42beWTMl4LCyWMKI8KvaeWqCNLHEAO2zBkpcAkm3GGNtcDUNOGp96VKR007PB4cdDD
stripe.public.key=pk_test_51Rfw5AQMuKMTVg9MN5UEzLULEZm4Q9xHqKAkAM8fRvmwPdL95kYt3Zh9c9h9XDRy5tBxQUumukXfH0LzvZ4jc5rJ00BaN3DtTC
stripe.webhook.secret = whsec_c8024d5aeA9e788AdSe1(Peee13e3c6f0eaBa1353366916aadF019eaf69rb32
spring.main.allow-bean-definition-overriding=true

